### ISSUE TITLE
歌詞と時間情報のAPI実装

### ISSUE THREAD

**Issue by mori-atsushi** [cyder-akashi/Aktiva-V2-Server#10]
https://api.aktiva-v2.cyder.tech/lyrics?song_id=<int>
歌詞と時間情報をjson形式で返す

```js
{
  song_id: <int>,
  lyrics:
    [{"time": <time>, "text": <int>],
    [{"time": <time>, "text": <int>],
  ...
}
```

## 実装方法
* db/seed.rbにテストデータを挿入
* lyricsコントローラ（app/controllers/api/v1/lyrics_controller.rb）を作成
* lyrics#indexビュー（app/views/api/v1/lyrics/index.json.jbuilder）を作成
* config/routesでルートを設定する
* lyrics#showアクションに対して、モデル・ビュー・コントローラを結合してテストを行う

## 完了条件
* http://localhost:3000/api/v1/lyrics?songId=<int>で上記のjsonが表示される
* アクセステスト（assert_response）が成功する

**Comment by chigichan24** [comment]
## 完了条件

+ https://api.aktiva-v2.cyder.tech/lyrics?song_id= で上記のjsonが表示される(update)
+ アクセステスト（assert_response）が成功する
