### ISSUE TITLE
Mroongaの導入

### ISSUE THREAD

**Issue by mori-atsushi** [cyder-akashi/Aktiva-V2-Server#31]
キーワード検索の精度を高める

主に以下のファイルの書き換えで対応する
app/models/search/base.rb（検索共通部分）
app/models/search/song.rb（楽曲検索で必要な部分）

参考：http://www.clear-code.com/blog/2015/11/10.html

**Comment by euglena1215** [comment]
@Mori-Atsushi @chigichan24 
doingのところ横槍を入れて申し訳ないんですが、
railsって割とDBに依存しなくてもいいようになってる(sqlite3 or mysql or postgresqlなど)
と思うんだけど、そこでMroongaを選択してmysqlに依存するようにしたのは理由がある？

有名どころの全文検索エンジンだと[elastic search](https://www.elastic.co/jp/products/elasticsearch)とかある中でMroongaを選んだ理由があれば知りたいかなって思います(こっちはDBに依存しない形になってたはず...)

**Comment by mori-atsushi** [comment]
ちょちょちょっと調べたらrailsとMroongaの相性良さそうだし、とりあえずこれ試してみるかって感じでしたね。
elastic searchはノーマークでした。
Mroongaについては @chigichan24 が調査中だったので、どちらが良さそうか決めていただけると。
両方試してみてもいいと思うけど。

**Comment by chigichan24** [comment]
@euglena1215 sqlに依存しすぎる感じはあるけど，依存している文柔軟度は高い．検索の自由度の将来性が不透明だったからいいかなと思ってた．elastic searchでも同様の自由度があるならそっちのほうらrailsらしくなるから乗り換えたい．

**Comment by euglena1215** [comment]
* そもそも何を求めて全文検索エンジンを導入するのかをはっきりさせたい
検索速度？その他？

elastic searchはfuzzy queryが使えるみたい
http://qiita.com/EastResident/items/5ebdd5d301838fd1be24

mroongaは表記揺れが辛そう
http://blog.createfield.com/entry/2015/11/30/120556

**Comment by mori-atsushi** [comment]
検索結果の妥当性重視かな
大事なのは曲の人気順じゃなくて、キーワードの関連度順に並ぶようにしたい
過去の検索結果とそこから何が選ばれたのかをフィードバックできるようなモデルがあるといいんだけど

**Comment by chigichan24** [comment]
Sunspot 全文検索はできる．
https://github.com/sunspot/sunspot

**Comment by mori-atsushi** [comment]
elastic searchに切り替えるので、このIssueは閉じますね。
