### ISSUE TITLE
db/schema.rbのスタイル修正

### ISSUE THREAD

**Issue by mori-atsushi** [cyder-akashi/Aktiva-V2-Server#43]
* hash記述の修正
* stringをシンボルに修正

**Comment by mori-atsushi** [comment]
具体的な解決策が見つかっていないので、ここで議論しましょう。

**Comment by chigichan24** [comment]
まず，導入の必要性として，古い記法は非推奨のメソッドを使っているくらい悪いことなので，排除しましょうというお話．

**Comment by chigichan24** [comment]
http://qiita.com/jnchito/items/b2e4289c5ae8bc1b2ee9

**Comment by chigichan24** [comment]
これでどうにかなりませんか？

**Comment by mori-atsushi** [comment]
一括変換ならrubocopにもついてるしって感じですね（ `rubocop --auto-correct` ）
どのタイミングで実行させるかが難しい
手動でやるのはめんどくさいし、なんかだめな気がする

**Comment by chigichan24** [comment]
ブランチ切るなら良いかなというかんじ．マージがコンフリクトの嵐になるけど．

**Comment by chigichan24** [comment]
そういうもんらしいので，はい．

**Comment by mori-atsushi** [comment]
僕が何度言っても許してくれなかったのに…（泣）
closeします。
