### ISSUE TITLE
rake db:seedするときに毎回消すのがめんどくさい

### ISSUE THREAD

**Issue by euglena1215** [cyder-akashi/Aktiva-V2-Server#47]
seedはcreateメソッドを使ってレコードを保存するのでレコードが追加される形になる。

そのためuniqueなcolumnが存在するとエラーが発生する。これが面倒。

## 解決策
1. `seeds.rb` の先頭で `delete_all` を実行する。
1.  [seed_fu](http://qiita.com/ko2ic/items/be96e450a33d631e0059)を導入する。

**Comment by mori-atsushi** [comment]
1のほうが好きかな

**Comment by euglena1215** [comment]
1での実装をtodoにしてもいいです？
