### ISSUE TITLE
データベースの作成

### ISSUE THREAD

**Issue by mori-atsushi** [cyder-akashi/Aktiva-V2-Server#6]
## songテーブル（曲情報）
* ☆song_id＜int＞
* title＜string＞
* artist_id＜int＞ → person.id
* lyricist_id＜int＞ → person.id
* composer_id＜int＞ → person.id
* choreographer_id＜int＞ → person.id
* beginners_badge＜bool＞
* person_badge＜bool＞

## personテーブル（アーティスト、作詞、作曲、振付師）
* ☆id＜int＞
* name＜string＞

## lyricsテーブル（歌詞）
* ☆song_id＜int＞ → song.song_id
* ☆time＜time(mm:ss.fff)＞
* text＜string＞

※ ☆は主キー

**Comment by mori-atsushi** [comment]
@chigichan24 テーブル構成図を作りました。適切かチェックしてくれると助かる。
特にlyricsテーブルが微妙…

**Comment by chigichan24** [comment]
personテーブル，のtextが何を示してるのかわからない．足りない気がする．

**Comment by mori-atsushi** [comment]
nameですね

**Comment by chigichan24** [comment]
ん？つまり， アーティスト，作詞，作曲，振付師，ぜんぶごちゃ混ぜでidふるの？

**Comment by mori-atsushi** [comment]
yes、そっちのほうがこの曲は作詞作曲は同じ人とか、この曲の作曲者がこの曲のアーティストとかわかりやすいなと思って

**Comment by chigichan24** [comment]
アーティスト，作詞，作曲，振付師って全部同一の情報で構成されているのだろうか．つまり，アーティスト画像とかそういう付加情報をこれ以上つけないの？そういう要素がそれぞれのPersonで異なるものをつけるならこの方針だと辛いことになると思う．

**Comment by mori-atsushi** [comment]
現状予定はないけど可能性はあるのかな…
アーティストだけが持つ情報があっても、アーティスト以外の人はNo Data（No Image）とかのデータ入れとけば問題ない気もする
同一人物が複数箇所にわかれて、それを紐付けるほうがだるいなと思って

**Comment by chigichan24** [comment]
それは一つのデータベースがでかくなりすぎて検索ゴミ遅くなりそうと思うのは僕だけかなぁ．

**Comment by mori-atsushi** [comment]
なるほどねぇ…
同一人物が複数箇所にわかれて、それを紐付ける方法を教えていただけると

**Comment by mori-atsushi** [comment]
更に検索は遅くなりそうだけど、付加情報に関する問題は以下の形式なら問題ない？

## Songテーブル
* song_id
* artist_id → artist.artist_id

## artistテーブル
* artist_id
* person_id → person.id
* アーティスト特有のデータ

## personテーブル
* person_id
* name

**Comment by chigichan24** [comment]
意外に紐付け面倒だなあ．確かにアーティストのデータテーブルを持てば良さそうな気もしてきたわ．

**Comment by mori-atsushi** [comment]
とりあえずは各々の特有データがないので、personテーブルに直でつなぐけど、特有データができたら間にテーブルかますってことでOK?

**Comment by chigichan24** [comment]
そうだね．
